### ISSUE TITLE
【1/17】配布物の手配

### ISSUE THREAD

**Issue by daichi-kashihara** [pinnacles/torm#13]
・手配して納品されたらチェックを入れる。
・現場に持っていく数量をコメントに記載する。

- [ ] tebikiパンフレット
- [ ] 現場改善ラボ
- [ ] 業界別導入事例
- [ ] Opp袋
- [ ] [【納期：1月17日】展示会配布用のSKPのチラシ制作 A4サイズ 1式#9564](https://github.com/pinnacles/tebiki/issues/9564)

**Comment by kakubin** [comment]
@daichi-kashihara 
issueの作成場所を間違えているようなので移動お願いします

**Comment by daichi-kashihara** [comment]
@kakubin
お手数おかけしてすみませんん。間違えて作成したようで削除したいのですが、どこで削除できるのかわからず……。クローズはできそうなのですが、クローズして問題ないものでしょうか……？

**Comment by kakubin** [comment]
@daichi-kashihara 削除はできないので一旦closeしてください

**Comment by daichi-kashihara** [comment]
@kakubin　承知しました。お手数おかけしました。

**Comment by daichi-kashihara** [comment]
@kakubin
スペースのみだとエラーになってできませんでした。一旦一文字にしてありますが、何にでも変更しますので指定あればください。お手数おかけしてすみません。
